jenkins:
  image: lstephen/jenkins-mylonelybear:latest
  ports:
    - 8080:8080
  links:
    - slave

slave:
  build: latest
  privileged: true
  links:
    - docker
  environment:
    - DOCKER_HOST=tcp://docker:2375
  volumes_from:
    - workspace

docker:
  image: lstephen/docker:latest
  privileged: true
  environment:
    - PORT=2375
  volumes_from:
    - workspace

workspace:
  image: lstephen/jenkins-workspace:latest
